# Binaries
debian/tmp/usr/sbin/monkey

# Configuration
debian/tmp/etc/monkey/monkey.conf
debian/tmp/etc/monkey/plugins.load
debian/tmp/etc/monkey/monkey.mime
debian/tmp/etc/monkey/sites/*

# Plugins setup
debian/tmp/etc/monkey/plugins/*

# Plugins / Libraries
debian/tmp/usr/lib/monkey/*.so

# WWW Data
debian/tmp/var/www/monkey/index.html
debian/tmp/var/www/monkey/favicon.ico
debian/tmp/var/www/monkey/imgs/monkey_logo.png

