name: Build PR(s)
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
    types: [opened, edited, synchronize]
jobs:
  build-windows:
    name: Build sources on amd64 for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 48
      fail-fast: false
      matrix:
        os: [windows-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Build on ${{ matrix.os }} with vs-2019
        run: |
          mkdir build
          cd build
          cmake -DMK_DEBUG=On -DMK_WITHOUT_BIN=On -DMK_WITHOUT_CONF=On -DMK_LIB_ONLY=On ..\
          cmake --build . --config Release

  build-unix:
    name: Build sources on amd64 for ${{ matrix.os }} - ${{ matrix.compiler }}
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 48
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        compiler: [ gcc, clang ]
        exclude:
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang
    steps:
      - uses: actions/checkout@v2
      - name: Build on ${{ matrix.os }} with ${{ matrix.compiler }}
        run: |
          mkdir build
          cd build
          echo "CC = $CC, CXX = $CXX"
          cmake -DMK_DEBUG=On -DMK_WITHOUT_BIN=On -DMK_WITHOUT_CONF=On -DMK_LIB_ONLY=On ../
          cmake --build .
        env:
          CC: ${{ matrix.compiler }}
